[package]
name = "cargo_features"
version = "0.1.0"
authors = ["yadaniel <ya.daniel@inbox.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libstrings = { git = "https://github.com/yadaniel/rust_libs.git" }

